import { storage } from "./storage";
import { log } from "./index";

const BASE = "https://vedam-nadam.org/wp-content/uploads";

const categoriesData = [
  { name: "Ganesha Stotrams", slug: "ganesha", description: "Devotional hymns dedicated to Lord Ganesha, the remover of obstacles", imageUrl: "/images/ganesha.png", sortOrder: 1 },
  { name: "Subramanya Stotrams", slug: "subramanya", description: "Sacred prayers to Lord Subramanya (Kartikeya), the commander of the divine army", imageUrl: "/images/subramanya.png", sortOrder: 2 },
  { name: "Siva Stotrams", slug: "shiva", description: "Devotional hymns to Lord Shiva, the destroyer and transformer", imageUrl: "/images/shiva.png", sortOrder: 3 },
  { name: "Vishnu Stotrams", slug: "vishnu", description: "Devotional hymns to Lord Vishnu, the preserver of the universe", imageUrl: "/images/vishnu.png", sortOrder: 4 },
  { name: "Devi Stotrams", slug: "devi", description: "Sacred prayers to the Divine Mother in her many forms", imageUrl: "/images/devi.png", sortOrder: 5 },
  { name: "Surya Stotrams", slug: "surya", description: "Sacred prayers to Surya, the Sun God and source of all energy", imageUrl: "/images/surya.png", sortOrder: 6 },
  { name: "Guru Stotrams", slug: "guru", description: "Devotional hymns honoring the spiritual teacher and guru lineage", imageUrl: "/images/guru.png", sortOrder: 7 },
  { name: "Hanuman Stotrams", slug: "hanuman", description: "Sacred prayers to Lord Hanuman, the embodiment of devotion and strength", imageUrl: "/images/hanuman.png", sortOrder: 8 },
];

interface StotramSeed {
  name: string;
  subcategory?: string;
  videoUrl?: string;
  teluguPdfUrl?: string;
  englishPdfUrl?: string;
  kannadaPdfUrl?: string;
  sanskritPdfUrl?: string;
}

const stotramsByCategory: Record<string, StotramSeed[]> = {
  ganesha: [
    { name: "Sri Ganesha Pancharatnam", videoUrl: "https://www.youtube.com/watch?v=ALIo0IrqyiE", teluguPdfUrl: `${BASE}/2024/08/Ganesha_Pancharatna_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Ganesha_Pancharatna_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Ganesha_Pancharatna_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Ganesha_Pancharatna_Stotram_Sanskrit.pdf` },
    { name: "Sankatanasana Ganesha Stotram", videoUrl: "https://youtu.be/kA6jcZrI_yk", teluguPdfUrl: `${BASE}/2024/08/Sankatanasana_Ganesha_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Sankatanasana_Ganesha_Stotram_Englsih.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Sankatanasana_Ganesha_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Sankatanasana_Ganesha_Stotram_Sanskrit.pdf` },
    { name: "Ganesha Pratahsmarami Stotram", videoUrl: "https://www.youtube.com/watch?v=oPPFytwtd6k", teluguPdfUrl: `${BASE}/2024/08/Ganesha_Pratahsmarana_Stotram.pdf`, englishPdfUrl: `${BASE}/2024/08/Ganesha_Pratahsmarami_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Ganesha_Pratahsmarana_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Ganesha_Pratahsmarana_Stotram_Sanskrit.pdf` },
    { name: "Ganesha Ekavimsathi Namavali", videoUrl: "https://www.youtube.com/watch?v=OhJM9tQTeOk", teluguPdfUrl: `${BASE}/2024/08/Ganesha_Ekavimsathi_Namavali_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Ganesha_Ekavimsathi_Namavali_Englisg.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Ganesha_Ekavimsathi_Namavali_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Ganesha_Ekavimsathi_Namavali_Sanskrit.pdf` },
  ],
  subramanya: [
    { name: "Subrahmanya Bhujamga Prayata Stotram", videoUrl: "https://youtu.be/41gMNI2J7ak", teluguPdfUrl: `${BASE}/2024/08/Subrahmanya_Bhujanga_Prayata_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Subrahmanya_Bhujanga_Prayata_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Subrahmanya_Bhujanga_Prayata_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Subrahmanya_Bhujanga_Prayata_Stotram_Sanskrit.pdf` },
    { name: "Pragna Vivardhana Karthikeya Stotram", videoUrl: "https://youtu.be/Hpp6SPE7yE4", teluguPdfUrl: `${BASE}/2024/08/Pragnavivardhana_Karthikeya_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Pragnavivardhana_Karthikeya_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Pragnavivardhana_Karthikeya_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Pragnavivardhana_Karthikeya_Stotram_Sanskrit.pdf` },
  ],
  shiva: [
    { name: "Chandrasekarashtakam", videoUrl: "https://www.youtube.com/watch?v=MU0mLvD5r38", teluguPdfUrl: `${BASE}/2024/09/Chandrasekara_Ashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Chandrasekara_Ashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Chandrasekara_Ashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Chandrasekara_Ashtakam_Sanskrit.pdf` },
    { name: "Dakshina Murthy Stotram", videoUrl: "https://youtu.be/uIFXAV_xnNI", teluguPdfUrl: `${BASE}/2024/09/Dakshinamurthy_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Dakshinamurthy_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Dakshinamurthy_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Dakshinamurthy_Stotram_Sanskrit.pdf` },
    { name: "Daridrya Dahana Siva Stotram", videoUrl: "https://youtu.be/U3Xvti_un-M", teluguPdfUrl: `${BASE}/2024/09/Daridradahana_Siva_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Daridradahana_Siva_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Daridradahana_Siva_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Daridradahana_Siva_Stotram_Sanskrit.pdf` },
    { name: "Dwadasa Jyothirlinga Stotram", teluguPdfUrl: `${BASE}/2024/09/Dwadasa_Jyothirlinga_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Dwadasa_Jyothirlinga_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Dwadasa_Jyothirlinga_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Dwadasa_Jyothirlinga_Stotram_Sanskrit.pdf` },
    { name: "Kalabhairavashtakam", videoUrl: "https://www.youtube.com/watch?v=Cs7QpsVf-rs", teluguPdfUrl: `${BASE}/2024/09/Kalabhairava_Ashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Kalabhairava_Ashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Kalabhairava_Ashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Kalabhairava_Ashtakam_Sanskrit.pdf` },
    { name: "Margabandhu Stotram", teluguPdfUrl: `${BASE}/2024/09/Margabandu_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Margabandu_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Margabandu_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Margabandu_Stotram_Sanskrit.pdf` },
    { name: "Nataraja Stotram", videoUrl: "https://youtu.be/9DOxfSCOJgc", teluguPdfUrl: `${BASE}/2024/09/Nataraja_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Nataraja_Stotram_English.pdf` },
    { name: "Siva Manasa Puja", teluguPdfUrl: `${BASE}/2024/09/Sivamanasa_Puja_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Sivamanasa_Puja_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Sivamanasa_Puja_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Sivamanasa_Puja_Sanskrit.pdf` },
    { name: "Siva Panchakshari Stotram", teluguPdfUrl: `${BASE}/2024/09/Sivapanchakshari_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Sivapanchakshari_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Sivapanchakshari_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Sivapanchakshari_Stotram_Sanskrit.pdf` },
    { name: "Sivamahimna Stotram", teluguPdfUrl: `${BASE}/2024/09/Sivamahimna_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Sivamahimna_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Sivamahimna_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Sivamahimna_Stotram_Sanskrit.pdf` },
    { name: "Sivamangalashtakam", teluguPdfUrl: `${BASE}/2024/09/Sivamangalashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Sivamangalashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Sivamangalashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Sivamangalashtakam_Sanskrit.pdf` },
    { name: "Sivanamavalyashtakam", teluguPdfUrl: `${BASE}/2024/09/Sivanamavali_Ashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Sivanamavali_Ashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Sivanamavali_Ashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Sivanamavali_Ashtakam_Sanskrit.pdf` },
    { name: "Sivananda Lahari", videoUrl: "https://youtu.be/B_1v77Qh00k" },
    { name: "Sivapanchakshara Nakshatramalika Stotram", videoUrl: "https://youtu.be/Z8LqUaDjVWQ", teluguPdfUrl: `${BASE}/2024/09/Sivapanchakshara_Nakshatramala_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Sivapanchakshara_Nakshatramala_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Sivapanchakshara_Nakshatramala_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Sivapanchakshara_Nakshatramala_Stotram_Sanskrit.pdf` },
    { name: "Siva Saharsranamam", teluguPdfUrl: `${BASE}/2026/01/Siva_Sahasranamam_Telugu.pdf`, englishPdfUrl: `${BASE}/2026/01/Siva_Sahasranamam_English.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Siva_Sahasranamam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Siva_Sahasranamam_Sanskrit.pdf` },
    { name: "Vaidyanathashtakam", teluguPdfUrl: `${BASE}/2024/09/Vydyanaashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Vydyanaashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Vydyanaashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Vydyanaashtakam_Sanskrit.pdf` },
  ],
  devi: [
    { name: "Argala Stotram", subcategory: "Durga Stotrams", teluguPdfUrl: `${BASE}/2024/09/Argala_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Argala_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Argala_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Argala_Stotram_Sanskrit.pdf` },
    { name: "Arjunakrutha Durga Stotram", subcategory: "Durga Stotrams", videoUrl: "https://www.youtube.com/watch?v=e3ZWIAYKZpk", teluguPdfUrl: `${BASE}/2024/09/Arjunakrutha_Durga_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Arjunakrutha_Durga_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Arjunakrutha_Durga_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Arjunakrutha_Durga_Stotram_Sanskrit.pdf` },
    { name: "Durga Chandrakala Sthuti", subcategory: "Durga Stotrams", videoUrl: "https://youtu.be/mSSj2A1tK8w", teluguPdfUrl: `${BASE}/2024/09/DurgaChandrakala_Stuti_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/DurgaChandrakala_Stuti_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/DurgaChandrakala_Stuti_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/DurgaChandrakala_Stuti_Sanskrit.pdf` },
    { name: "Durga Dwatrisan Namavali Stotram", subcategory: "Durga Stotrams", videoUrl: "https://www.youtube.com/watch?v=C6cJTG8EMo8", teluguPdfUrl: `${BASE}/2024/09/Durga_Dwatrisan_Namavali_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Durga_Dwatrisan_Namavali_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Durga_Dwatrisan_Namavali_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Durga_Dwatrisan_Namavali_Sanskrit.pdf` },
    { name: "Durga Pancharatna Stotram", subcategory: "Durga Stotrams", videoUrl: "https://youtu.be/uBm5kEwvXZA", teluguPdfUrl: `${BASE}/2025/04/Durga_Pancharatna_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2026/01/Durga_Puncharatna_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Durga_Puncharatna_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Durga_Puncharatna_Stotram_Sanskrit.pdf` },
    { name: "Kanakadurgananda Lahari", subcategory: "Durga Stotrams", kannadaPdfUrl: `${BASE}/2024/09/Sri_Kanakadurgaanandalahari_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Sri_Kanakadurgaanandalahari_Sanskrit.pdf` },
    { name: "Kumari Stotram", subcategory: "Durga Stotrams", teluguPdfUrl: `${BASE}/2024/12/Kumari_Stotram_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Kumari_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Kumari_Stotram_Sanskrit.pdf` },
    { name: "Mahishasura Mardhini Stotram", subcategory: "Durga Stotrams", teluguPdfUrl: `${BASE}/2024/12/Mahishasura_Mardhini_Stotram_Telugu-1.pdf` },
    { name: "Gayatri Bhujamga Stotram", subcategory: "Gayatri / Sarada / Syamala Stotrams", teluguPdfUrl: `${BASE}/2024/12/Gayatri_Bhujanga_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/GayatriBhujangaStotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Gayatri_Bhujanga_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Gayatri_Bhujanga_Stotram_Sanskrit.pdf` },
    { name: "Sarada Bhujamga Prayata Ashtakam", subcategory: "Gayatri / Sarada / Syamala Stotrams", teluguPdfUrl: `${BASE}/2024/12/Sarada_Bhujamga_Prayata_Ashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Sarada_Bhujamga_Ashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Sarada_Bhujamga_Prayata_Ashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Sarada_Bhujamga_Prayata_Ashtakam_Sanskrit.pdf` },
    { name: "Syamala Dandakam", subcategory: "Gayatri / Sarada / Syamala Stotrams", teluguPdfUrl: `${BASE}/2024/12/Syamala_Dandakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Syamala_Dandakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Syamala_Dandakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Syamala_Dandakam_Sanskrit.pdf` },
    { name: "Syamala Navaratnamalika Stavam", subcategory: "Gayatri / Sarada / Syamala Stotrams", videoUrl: "https://youtu.be/eiviSlkwzTw", teluguPdfUrl: `${BASE}/2026/01/Syamala_Navaratnamalika_Stavam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Syamala_Navaratnamalika_Stavam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Syamala_Navaratnamalika_Stavam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Syamala_Navaratnamalika_Stavam_Sanskrit.pdf` },
    { name: "Anandalahari", subcategory: "Kamakshi / Lalitha Stotrams", teluguPdfUrl: `${BASE}/2024/12/Anandalahari_Telugui.pdf`, englishPdfUrl: `${BASE}/2024/12/Anandalahari_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Anandalahari_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Anandalahari_Sanskrit.pdf` },
    { name: "Istakamesvari Stotram", subcategory: "Kamakshi / Lalitha Stotrams", videoUrl: "https://www.youtube.com/watch?v=RkVX7MFA_ck", teluguPdfUrl: `${BASE}/2024/12/Ishtakameswari_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Ishtakameswari_Stotram_Englsih.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Ishtakameswari_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Ishtakameswari_Stotram_Sanskrit.pdf` },
    { name: "Kalyanavrushti Stavam", subcategory: "Kamakshi / Lalitha Stotrams", teluguPdfUrl: `${BASE}/2024/12/Kalyanavrushti_Stavam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Anandalahari_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Kalyanavrushti_Stavam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Kalyanavrushti_Stavam_Sanskrit.pdf` },
    { name: "Kamesvaryastakam", subcategory: "Kamakshi / Lalitha Stotrams", videoUrl: "https://www.youtube.com/watch?v=pPNsuJH_meE", teluguPdfUrl: `${BASE}/2024/12/Kaamesvaryashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Kaamesvaryashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Kaamesvaryashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Kaamesvaryashtakam_Sanskrit.pdf` },
    { name: "Kamakshi Churnika", subcategory: "Kamakshi / Lalitha Stotrams", teluguPdfUrl: `${BASE}/2024/12/Kamakshi_Choornika_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Kamakshi_Choornika_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Kamakshi_Choornika_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Kamakshi_Choornika_Sanskrit.pdf` },
    { name: "Kamakshi Stotram - 1", subcategory: "Kamakshi / Lalitha Stotrams", teluguPdfUrl: `${BASE}/2024/12/Kamakshi_Stotram_1_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Kamakshi_Stotram_1_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Kamakshi_Stotram_1_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Kamakshi_Stotram_1_Sanskrit.pdf` },
    { name: "Kamakshi Stotram - 2", subcategory: "Kamakshi / Lalitha Stotrams", teluguPdfUrl: `${BASE}/2024/12/Kamakshi_Stotram_2_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Kamakshi_Stotram_2_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Kamakshi_Stotram_2_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Kamakshi_Stotram_2_Sanskrit.pdf` },
    { name: "Lalitha Avirbhava Stuti", subcategory: "Kamakshi / Lalitha Stotrams", videoUrl: "https://youtu.be/ThcCs4jVo68", teluguPdfUrl: `${BASE}/2026/01/Lalitha_Avirbhava_Stuti_Telugu.pdf`, englishPdfUrl: `${BASE}/2026/01/Lalitha_Avirbhava_Stuti_English.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Lalitha_Avirbhava_Stuti_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Lalitha_Avirbhava_Stuti_Sanskrit.pdf` },
    { name: "Lalita Pancharatna Stotram", subcategory: "Kamakshi / Lalitha Stotrams", teluguPdfUrl: `${BASE}/2024/09/Lalitha_Pancharatnam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Lalitha_Pancharatnam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Lalitha_Pancharatnam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Lalitha_Pancharatnam_Sanskrit.pdf` },
    { name: "Bala Stotram", subcategory: "Kamakshi / Lalitha Stotrams" },
    { name: "Lalitha Sahasranamam", subcategory: "Kamakshi / Lalitha Stotrams", videoUrl: "https://www.youtube.com/watch?v=Wy3ThWhR8-A&t=14s" },
    { name: "Mookapanchasathi - Arya Satakam", subcategory: "Kamakshi / Lalitha Stotrams", kannadaPdfUrl: `${BASE}/2026/01/Arya_Sathakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Arya_Sathakam_Sanskrit.pdf` },
    { name: "Mookapanchasathi - Paadaravinda Satakam", subcategory: "Kamakshi / Lalitha Stotrams", kannadaPdfUrl: `${BASE}/2026/01/Paadaravinda_Sathakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Paadaravinda_Sathakam_Sanskrit.pdf` },
    { name: "Mookapanchasathi - Sthuti Satakam", subcategory: "Kamakshi / Lalitha Stotrams", kannadaPdfUrl: `${BASE}/2026/01/Sthuti_Sathakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Sthuti_Sathakam_Sanskrit.pdf` },
    { name: "Mookapanchasathi - Kataksha Satakam", subcategory: "Kamakshi / Lalitha Stotrams", kannadaPdfUrl: `${BASE}/2026/01/Kataksha_Sathakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Kataksha_Sathakam_Sanskrit.pdf` },
    { name: "Mookapanchasathi - Mandasmitha Satakam", subcategory: "Kamakshi / Lalitha Stotrams", kannadaPdfUrl: `${BASE}/2026/01/Mandasmitha_Sathakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Mandasmitha_Sathakam_Sanskrit.pdf` },
    { name: "Rajarajeswari Mantramalika Stotram", subcategory: "Kamakshi / Lalitha Stotrams", teluguPdfUrl: `${BASE}/2024/09/Rajarajeswari_Mantramalika_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Rajarajeswari_Mantramalika_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Rajarajeswari_Mantramalika_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Rajarajeswari_Mantramalika_Stotram_Sanskrit.pdf` },
    { name: "Soundaryalahari Stotram", subcategory: "Kamakshi / Lalitha Stotrams", videoUrl: "https://www.youtube.com/watch?v=X2UUQCUrm-c" },
    { name: "Tripuraa Tilaka Stotram", subcategory: "Kamakshi / Lalitha Stotrams", teluguPdfUrl: `${BASE}/2024/09/Tripuraa_Tilaka_Stotram_Telugu-1.pdf`, englishPdfUrl: `${BASE}/2024/09/Tripuraa_Tilaka_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Tripuraa_Tilaka_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Tripuraa_Tilaka_Stotram_Sanskrit.pdf` },
    { name: "Kanakadhara Stotram", subcategory: "Lakshmi Stotrams", teluguPdfUrl: `${BASE}/2025/03/Kanakadara_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Kanakadara_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2025/03/Kanakadara_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/03/Kanakadara_Stotram_Sanskrit.pdf` },
    { name: "Lakshmi Astottara Satanama Stotram", subcategory: "Lakshmi Stotrams", teluguPdfUrl: `${BASE}/2024/09/Lakshmi_AshotaraSathanam_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Lakshmi_AshotaraSathanam_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Lakshmi_AshotaraSathanam_Stotram_Kannada-1.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Lakshmi_AshotaraSathanam_Stotram_Sanskrit-1.pdf` },
    { name: "Lakshmi Hrudyam", subcategory: "Lakshmi Stotrams" },
    { name: "Sri Mahalakshmi Ashtakam", subcategory: "Lakshmi Stotrams", videoUrl: "https://www.youtube.com/watch?v=NbYApLOy0u8", teluguPdfUrl: `${BASE}/2024/09/Mahalakshmaashtakam_Indrakruta_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Mahalakshmaashtakam_Indrakruta_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Mahalakshmaashtakam_Indrakruta_Kannada-1.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Mahalakshmaashtakam_Indrakruta_Sanskeit-1.pdf` },
    { name: "Mahalakshmi Chaturvimsa Namavali", subcategory: "Lakshmi Stotrams", videoUrl: "https://youtu.be/7768brBRgn8", teluguPdfUrl: `${BASE}/2024/09/Mahalakshmi_Chaturvimsa_Namavali_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Mahalakshmi_Chaturvimsa_Namavali_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Mahalakshmi_Chaturvimsa_Namavali_Kannada-1.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Mahalakshmi_Chaturvimsa_Namavali_Sanskrit-1.pdf` },
    { name: "Mahalakshmi Stotram Vishnupuranam", subcategory: "Lakshmi Stotrams", teluguPdfUrl: `${BASE}/2024/09/Mahalakshmi_Stotram_Vishnupuranam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Mahalakshmi_Stotram_Vishnupurana_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Mahalakshmi_Stotram_Vishnupuranam_Kannada-1.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Mahalakshmi_Stotram_Vishnupuranam_Sanskrit-1.pdf` },
    { name: "Viswa Raksha Kavacha Namavali", subcategory: "Lakshmi Stotrams", videoUrl: "https://www.youtube.com/watch?v=uHqFq-QU0nk", teluguPdfUrl: `${BASE}/2024/12/Viswaraksha_Kavacha_Namavali_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Viswaraksha_Kavacha_Namavali_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Viswaraksha_Kavacha_Namavali_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Viswaraksha_Kavacha_Namavali_Sanskrit.pdf` },
    { name: "Bhavani Ashtakam", subcategory: "Parvati Stotrams", teluguPdfUrl: `${BASE}/2024/09/Bhavani_Ashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Bhavani_Ashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Bhavani_Ashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Bhavani_Ashtakam_Sanskrit.pdf` },
    { name: "Devi Asvadhati Stotram", subcategory: "Parvati Stotrams", teluguPdfUrl: `${BASE}/2024/09/Devi_Aswadati_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Devi_Aswadati_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Devi_Aswadati_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Devi_Aswadati_Stotram_Sanskrit.pdf` },
    { name: "Garbharaksha Stotram", subcategory: "Parvati Stotrams", videoUrl: "https://www.youtube.com/watch?v=38dJUx4xe_g", teluguPdfUrl: `${BASE}/2024/09/Garbharaksha_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Garbharaksha_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Garbharaksha_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Garbharaksha_Stotram_Sanskrit.pdf` },
    { name: "Gouri Dasakam", subcategory: "Parvati Stotrams", teluguPdfUrl: `${BASE}/2024/09/Gouri_Dasakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Gouri_Dasakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Gouri_Dasakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Gouri_Dasakam_Sanskrit.pdf` },
    { name: "Mangala Chandika Stotram", subcategory: "Parvati Stotrams", videoUrl: "https://www.youtube.com/watch?v=01O2ssXCmmI", teluguPdfUrl: `${BASE}/2024/09/MangalaChandi_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/MangalaChandi_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/MangalaChandi_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/MangalaChandi_Stotram_Sanskrit.pdf` },
    { name: "Navaratnamalika Stotram", subcategory: "Parvati Stotrams", teluguPdfUrl: `${BASE}/2024/09/NavaratnaMalika_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/NavaratnaMalika_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/NavaratnaMalika_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/NavaratnaMalika_Stotram_Sanskrit.pdf` },
    { name: "Swayamvara Parvati Mantramala Stotram", subcategory: "Parvati Stotrams", teluguPdfUrl: `${BASE}/2024/12/Swayamvara_Parvati_Mantramala_Stotram_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Swayamvara_Parvati_Mantramala_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Swayamvara_Parvati_Mantramala_Stotram_Sanskrit.pdf` },
    { name: "Maanasa Devi Dwadasanama Stotram", subcategory: "Other Devi Stotrams", videoUrl: "https://www.youtube.com/watch?v=8V307WtMbCk", teluguPdfUrl: `${BASE}/2024/12/Maanasa_Devi_Dwadasanama_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Maanasa_Devi_Dwadasanama_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Maanasa_Devi_Dwadasanama_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Maanasa_Devi_Dwadasanama_Stotram_Sanskrit.pdf` },
    { name: "Meenakshi Pancharatnam Stotram", subcategory: "Other Devi Stotrams", teluguPdfUrl: `${BASE}/2024/12/Meenakshi_Pancharatnam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Meenakshi_Pancharatnam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Meenakshi_Pancharatnam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Meenakshi_Pancharatnam_Sanskrit.pdf` },
    { name: "Tulasi Stotram", subcategory: "Other Devi Stotrams", teluguPdfUrl: `${BASE}/2024/12/Tulasi_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Tulasi_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Tulasi_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Tulasi_Stotram_Sanskrit.pdf` },
    { name: "Varahai Sthuti Stotram", subcategory: "Other Devi Stotrams", teluguPdfUrl: `${BASE}/2024/12/Varahai_Sthuti_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/Varahai_Sthut_Englishi.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Varahai_Sthuti_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Varahai_Sthuti_Sanskrit.pdf` },
    { name: "Ganga Stotram", subcategory: "Nadi Stotrams" },
    { name: "Godavari Stotram", subcategory: "Nadi Stotrams" },
    { name: "Narmadastakam", subcategory: "Nadi Stotrams" },
    { name: "Yamunastakam", subcategory: "Nadi Stotrams" },
  ],
  vishnu: [
    { name: "Govindashtakam" },
    { name: "Hayagreeva Stotram", teluguPdfUrl: `${BASE}/2024/09/Hayagreeva_Storam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/HayagrIvaStoram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Hayagreeva_Storam_Kannada-1.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Hayagreeva_Storam_Sanskrit.pdf` },
    { name: "Krishnashtakam" },
    { name: "Lakshmi Narasimha Pancharatnam", teluguPdfUrl: `${BASE}/2024/09/LakshmiNarasimha_Pancharatnam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/LakshmiNarasimha_Pancharatnam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/LakshmiNarasimha_Pancharatnam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/LakshmiNarasimha_Pancharatnam_Sanskrit.pdf` },
    { name: "Lakshmi Nrusimha Karavalamba Stotram", teluguPdfUrl: `${BASE}/2024/09/Laskhmi_Nrusimha_Karavalamba_Stotram_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Laskhmi_Nrusimha_Karavalamba_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Laskhmi_Nrusimha_Karavalamba_Stotram_Sanskrit.pdf` },
    { name: "Madhurashtakam", teluguPdfUrl: `${BASE}/2026/01/Maduraashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2026/01/Maduraashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Maduraashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Maduraashtakam_Sanskrit.pdf` },
    { name: "Medipur Narasimhaswami Suprabhatam", teluguPdfUrl: `${BASE}/2025/11/Medipur_Narasimhaswami_Suprabhatam_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/11/Medipur_Narasimhaswami_Suprabhatam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/11/Medipur_Narasimhaswami_Suprabhatam_Sanskrit.pdf` },
    { name: "Mukundamala", teluguPdfUrl: `${BASE}/2024/09/Mukundamala_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Mukundamala_Kannada-1.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Mukundamala_Sanskrit-1.pdf` },
    { name: "Narayana Hrudayam", teluguPdfUrl: `${BASE}/2024/09/Narayana_Hrudayam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Narayana_Hrudayam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Narayana_Hrudayam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Narayana_Hrudayam_Sanskrit.pdf` },
    { name: "Runavimochana Narasimha Stotram", teluguPdfUrl: `${BASE}/2024/09/Runavimochana-_Narasimha_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Runavimochana-_Narasimha_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Runavimochana-_Narasimha_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Runavimochana-_Narasimha_Stotram_Sanskrit.pdf` },
    { name: "Sudarsanashtakam", teluguPdfUrl: `${BASE}/2024/09/Sudarsanashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Sudarsanashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Sudarsanashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Sudarsanashtakam_Sanskrit.pdf` },
    { name: "Venkateswara Ashtakam", teluguPdfUrl: `${BASE}/2024/09/Venkateswara_Ashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Venkateswara_Ashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Venkateswara_Ashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Venkateswara_Ashtakam_Sanskrit.pdf` },
    { name: "Vishnu Shatpadi Stotram", videoUrl: "https://www.youtube.com/watch?v=cb1a4cEUEW0", teluguPdfUrl: `${BASE}/2024/09/Vishnushatpadi_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/09/Vishnushatpadi_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Vishnushatpadi_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Vishnushatpadi_Stotram_Sanskrit.pdf` },
    { name: "Adivaraha Stotram", videoUrl: "https://www.youtube.com/watch?v=dzFgPLj8PHU", teluguPdfUrl: `${BASE}/2024/12/Adivaraha_Stotram_Bhudevikruta_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2024/12/Adivaraha_Stotram_Bhudevikruta_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/Adivaraha_Stotram_Bhudevikruta_Sanskrit.pdf` },
    { name: "Dasakam 0 – Narayaneeyam Introduction by Prof. Dr. Dhoolypala Ramakrishna Garu", videoUrl: "https://youtu.be/AVRbGDATg2k", subcategory: "Narayaneeyam" },
    { name: "Dasakam 1 – Bḥagavaṯ Mahimā", videoUrl: "https://youtu.be/fPuVSjaONBo", teluguPdfUrl: `${BASE}/2025/12/Dasakam1_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam1_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam1_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 2 – Bḥagavaṯ Svarūpā Bhākthī Mahṯvamu", videoUrl: "https://youtu.be/o4V5GOyxiDM", teluguPdfUrl: `${BASE}/2025/12/Dasakam2_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam2_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam2_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 3 – Bḥagavaṯ Svarūpā Varnanamu", videoUrl: "https://youtu.be/MRB_XGRMStM", teluguPdfUrl: `${BASE}/2025/12/Dasakam3_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam3_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam3_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 4 – Ashtāng̱yōgasidhī varnanamu", videoUrl: "https://youtu.be/HeCLu-GSCj4", teluguPdfUrl: `${BASE}/2025/12/Dasakam4_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam4_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam4_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 5 – Virāṭpuruṣōtpattiḥ", videoUrl: "https://youtu.be/NAqmdfWvCIc", teluguPdfUrl: `${BASE}/2025/12/Dasakam5_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam5_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam5_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 6 – Virāṭpuruṣudu Jagadātma Tatvam", videoUrl: "https://youtu.be/-18OppiqcxM", teluguPdfUrl: `${BASE}/2025/12/Dasakam6_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam6_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam6_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 7 – Hīranyagarbhōtpattiḥ", videoUrl: "https://youtu.be/gRouUhUIUrI", teluguPdfUrl: `${BASE}/2025/12/Dasakam7_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam7_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam7_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 8 – Pralayavarṇanamu", videoUrl: "https://youtu.be/23Gu1uc7z_U", teluguPdfUrl: `${BASE}/2025/12/Dasakam8_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam8_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam8_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 9 – Jagathṣrṣtiḥ Prakāra̱ Varṇanamu", videoUrl: "https://youtu.be/l2vZbA5el_Q", teluguPdfUrl: `${BASE}/2025/12/Dasakam9_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam9_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam9_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 10 – Sṛsībeda Varṇanamu", videoUrl: "https://youtu.be/JqswigIqugs", teluguPdfUrl: `${BASE}/2025/12/Dasakam10_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam10_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam10_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 11 – Hiraṇyāksha – Hiraṇyakaśipula Uthpathī", videoUrl: "https://youtu.be/i39MnD02ZGk", teluguPdfUrl: `${BASE}/2025/12/Dasakam11_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam11_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam11_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 12 – Varāhāvatāram", videoUrl: "https://youtu.be/RTFtfBwVeDQ", teluguPdfUrl: `${BASE}/2025/12/Dasakam12_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam12_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam12_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 13 – Hiraṇyākṣavadha", videoUrl: "https://youtu.be/hKFg71rRP0o", teluguPdfUrl: `${BASE}/2025/12/Dasakam13_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam13_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam13_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 14 – Kapilōpākhyānam", videoUrl: "https://youtu.be/MIQKsJYFyuM", teluguPdfUrl: `${BASE}/2025/12/Dasakam14_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam14_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam14_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 15 – Kapilōpadēśam", videoUrl: "https://youtu.be/J-mL-1ujILg", teluguPdfUrl: `${BASE}/2025/12/Dasakam15_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam15_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam15_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 16 – Naranārāyanāvathāram̍", videoUrl: "https://youtu.be/b34QxHiwyd8", teluguPdfUrl: `${BASE}/2025/12/Dasakam16_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam16_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam16_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 17 – Dhruva Caritam", videoUrl: "https://youtu.be/whhDzzKNtgE", teluguPdfUrl: `${BASE}/2025/12/Dasakam17_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam17_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam17_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 18 – Pṛthu Caritam", videoUrl: "https://youtu.be/saDFAFnLspk", teluguPdfUrl: `${BASE}/2025/12/Dasakam18_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam18_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam18_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 19 – Prachētásulu Katha", videoUrl: "https://youtu.be/ZNXRQfBp1Z8", teluguPdfUrl: `${BASE}/2025/12/Dasakam19_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam19_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam19_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 20 – Ṛṣabhasula Caritam", videoUrl: "https://youtu.be/aoYf0Mh9EQg", teluguPdfUrl: `${BASE}/2025/12/Dasakam20_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam20_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam20_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 21 – Jambu Dvīpam – Bhagavad́ Upāsanā", videoUrl: "https://youtu.be/XgPzUArExc0", teluguPdfUrl: `${BASE}/2025/12/Dasakam21_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam21_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam21_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 22 – Ajāmilopākhyānam", videoUrl: "https://youtu.be/TaT58SOenfY", teluguPdfUrl: `${BASE}/2025/12/Dasakam22_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam22_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam22_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 23 – Citraketōpākhyānam", videoUrl: "https://youtu.be/Dr-jbDdK5bQ", teluguPdfUrl: `${BASE}/2025/12/Dasakam23_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam23_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam23_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 24 – Prahlād Caritam", videoUrl: "https://youtu.be/zRn0djOFw7c", teluguPdfUrl: `${BASE}/2025/12/Dasakam24_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam24_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam24_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 25 – Sri Nrusimhāvatāram", videoUrl: "https://youtu.be/mq8bhg7LBZQ", teluguPdfUrl: `${BASE}/2025/12/Dasakam25_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam25_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam25_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 26 – Gajēndramōkṣam", videoUrl: "https://youtu.be/X1RVoJYbAuc", teluguPdfUrl: `${BASE}/2025/12/Dasakam26_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam26_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam26_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 27 – Kūrmāvatāram", videoUrl: "https://youtu.be/8PsCniZX9Jk", teluguPdfUrl: `${BASE}/2025/12/Dasakam27_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam27_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam27_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 28 – Lakṣhmīsavyam̍varam – Amrutōtpattiḥ", videoUrl: "https://youtu.be/_jONJ9KD60I", teluguPdfUrl: `${BASE}/2025/12/Dasakam28_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam28_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam28_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 29 – Mōhiniavatāram", videoUrl: "https://youtu.be/Tkm5pww-W5M", teluguPdfUrl: `${BASE}/2025/12/Dasakam29_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam29_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam29_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 30 – Vāmanāvatāram", videoUrl: "https://youtu.be/zcs8XoxceoM", teluguPdfUrl: `${BASE}/2025/12/Dasakam30_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam30_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam30_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 31 – Bali Darpaśamanam", videoUrl: "https://youtu.be/iH_XjZTWCmQ", teluguPdfUrl: `${BASE}/2025/12/Dasakam31_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam31_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam31_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 32 – Matsyāvatāram", videoUrl: "https://youtu.be/sgMDZirwVtU", teluguPdfUrl: `${BASE}/2025/12/Dasakam32_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam32_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam32_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 33 – Aṃbarēsōpākhyānam", videoUrl: "https://youtu.be/Yf-pKg599hw", teluguPdfUrl: `${BASE}/2025/12/Dasakam33_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam33_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam33_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 34 – Srī Rāmāvatāram – 1", videoUrl: "https://youtu.be/XxUr-9V25Ig", teluguPdfUrl: `${BASE}/2025/12/Dasakam34_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam34_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam34_Sankrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 35 – Srī Rāmāvatāram – 2", videoUrl: "https://youtu.be/II1lKhVZCt4", teluguPdfUrl: `${BASE}/2025/12/Dasakam35_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam35_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam35_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 36 – Paraśurāmāvatāram", videoUrl: "https://youtu.be/qTUMMSZJC8s", teluguPdfUrl: `${BASE}/2025/12/Dasakam36_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam36_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam36_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 37 – Śrikṛṣnāvatāram", videoUrl: "https://youtu.be/ydGSziMUR2s", teluguPdfUrl: `${BASE}/2025/12/Dasakam37_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam37_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam37_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 38 – Śrikṛṣnāvatāram – Gokulam", videoUrl: "https://youtu.be/cVQ8sdulyqA", teluguPdfUrl: `${BASE}/2025/12/Dasakam38_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam38_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam38_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 39 – Yogamāyā Varnanam", videoUrl: "https://youtu.be/Kwd5ggH0T68", teluguPdfUrl: `${BASE}/2025/12/Dasakam39_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam39_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam39_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 40 – Pūtana Vadha", videoUrl: "https://youtu.be/CfgnQuk8dwY", teluguPdfUrl: `${BASE}/2025/12/Dasakam40_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam40_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam40_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 41 – Gopīkānandahēlam", videoUrl: "https://youtu.be/ZfFTRVopdfU", teluguPdfUrl: `${BASE}/2025/12/Dasakam41_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam41_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam41_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 42 – Śakatāsura Vadha", videoUrl: "https://youtu.be/--9WI9weS4E", teluguPdfUrl: `${BASE}/2025/12/Dasakam42_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam42_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam42_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 43 – Tṛṇāvarta Vadha", videoUrl: "https://youtu.be/0OIFHYErUpQ", teluguPdfUrl: `${BASE}/2025/12/Dasakam43_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam43_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam43_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 44 – Jātakarmadī Sam̍skram", videoUrl: "https://youtu.be/FL8i3Tqpbgw", teluguPdfUrl: `${BASE}/2025/12/Dasakam44_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam44_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam44_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 45 – Śrikṛīshnā Balyakr̄dadi", videoUrl: "https://youtu.be/bTdeuuAvPlQ", teluguPdfUrl: `${BASE}/2025/12/Dasakam45_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam45_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam45_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 46 – Viśvarōpadarśanam", videoUrl: "https://youtu.be/6T63-kwcM_w", teluguPdfUrl: `${BASE}/2025/12/Dasakam46_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam46_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam46_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 47 – Ulūkhalabandhanam", videoUrl: "https://youtu.be/s_9P8aBgaS0", teluguPdfUrl: `${BASE}/2025/12/Dasakam47_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam47_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam47_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 48 – Yamlārjunōddhāram", videoUrl: "https://youtu.be/uKWlCktIXpM", teluguPdfUrl: `${BASE}/2025/12/Dasakam48_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam48_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam48_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 49 – Bṛṇdāvanavihāram", videoUrl: "https://youtu.be/6moycGWwfs0", teluguPdfUrl: `${BASE}/2025/12/Dasakam49_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam49_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam49_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 50 – Vatsāsura – Bakāsura Vadha", videoUrl: "https://youtu.be/NOvTaEvSSF8", teluguPdfUrl: `${BASE}/2025/12/Dasakam50_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/12/Dasakam50_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/12/Dasakam50_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 51 – Aghāsurāvadham", videoUrl: "https://youtu.be/JHmbo-a5FdA", teluguPdfUrl: `${BASE}/2025/12/Dasakam51_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam51_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam51_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 52 – Brahmakṛta Vatsāpharanam", videoUrl: "https://youtu.be/8UkMnhHPJig", teluguPdfUrl: `${BASE}/2026/01/Dasakam52_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam52_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam52_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 53 – Dhēnukāsuravadha", videoUrl: "https://youtu.be/2a0_xBr8Ju0", teluguPdfUrl: `${BASE}/2025/12/Dasakam53_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam53_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam53_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 54 – Kāliyopakhyanam", videoUrl: "https://youtu.be/uBmgnaOAI70", teluguPdfUrl: `${BASE}/2025/12/Dasakam54_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam54_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam54_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 55 – Kāliyamardhanam", videoUrl: "https://youtu.be/A_NLIzrmvFc", teluguPdfUrl: `${BASE}/2025/12/Dasakam55_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam55_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam55_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 56 – Kāliyagarvaśamanam – Bhagavaḍanugraham", videoUrl: "https://youtu.be/ONtCN7ZLFUw", teluguPdfUrl: `${BASE}/2025/12/Dasakam56_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam56_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam56_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 57 – Pralambasura Vadha", videoUrl: "https://youtu.be/GotD1yTfC7Y", teluguPdfUrl: `${BASE}/2025/12/Dasakam57_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam57_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam57_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 58 – Dāvāgnisaṃrkaṣanaṃ", videoUrl: "https://youtu.be/RJF-P4uWXEU", teluguPdfUrl: `${BASE}/2025/12/Dasakam58_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam58_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam58_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 59 – Venugānavarananam", videoUrl: "https://youtu.be/HR3j43hVMF4", teluguPdfUrl: `${BASE}/2026/01/Dasakam59_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam59_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam59_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 60 – Gopikavastraupaharanam", videoUrl: "https://youtu.be/-7xl-BvxCqk", teluguPdfUrl: `${BASE}/2025/12/Dasakam60_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam60_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam60_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 61 – Viprapatnianugraham", videoUrl: "https://youtu.be/JH8qdykDsrI", teluguPdfUrl: `${BASE}/2025/12/Dasakam61_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam61_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam61_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 62 – Indrayagnanivaaranam", videoUrl: "https://youtu.be/DZ0h-6plDlo", teluguPdfUrl: `${BASE}/2025/12/Dasakam62_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam62_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam62_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 63 – Govardhanodharaṇam", videoUrl: "https://youtu.be/K6eNsinX1bk", teluguPdfUrl: `${BASE}/2026/01/Dasakam63_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam63_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam63_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 64 – Govindapaṭābhiṣekam", videoUrl: "https://youtu.be/oiq-g7fVTzc", teluguPdfUrl: `${BASE}/2025/12/Dasakam64_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam64_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam64_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 65 – Rāsakriḍāyāṃ Gopīnāṃ Prapatye", videoUrl: "https://youtu.be/MpNAF1MmF_Q", teluguPdfUrl: `${BASE}/2025/12/Dasakam65_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam65_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam65_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 66 – Rāsakriḍā", videoUrl: "https://youtu.be/yRIn6Hhceg8", teluguPdfUrl: `${BASE}/2025/12/Dasakam66_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam66_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam66_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 67 – SriKriśanāṃtaradhānam", videoUrl: "https://youtu.be/cRkXEQWsJsw", teluguPdfUrl: `${BASE}/2025/12/Dasakam67_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam67_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam67_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 68 – Bhagavatsākśatkāram", videoUrl: "https://youtu.be/stC7zwx70go", teluguPdfUrl: `${BASE}/2025/12/Dasakam68_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam68_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam68_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 69 – Rāsakeli", videoUrl: "https://youtu.be/zmMnCehANuA", teluguPdfUrl: `${BASE}/2026/01/Dasakam69_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam69_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam69_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 70 – Sudarśanaśāpamokṣādīvarṇanam –Sankhacūḍa-arisṭavadham", videoUrl: "https://youtu.be/F298yT0oLRw", teluguPdfUrl: `${BASE}/2025/12/Dasakam70_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam70_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam70_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 71 – Kesi – Vyomasuravadha", videoUrl: "https://youtu.be/7QxPXTDme9E", teluguPdfUrl: `${BASE}/2025/12/Dasakam71_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam71_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam71_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 72 – Akrūraāgamanam", videoUrl: "https://youtu.be/uqBsE0PrCrU", teluguPdfUrl: `${BASE}/2025/12/Dasakam72_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam72_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam72_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 73 – Mathurāyāṭrā", videoUrl: "https://youtu.be/cvwLy8c5o1A", teluguPdfUrl: `${BASE}/2026/01/Dasakam73_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam73_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam73_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 74 – Mathurarāpuri Srikrisṇ Leelāvilāsam", videoUrl: "https://youtu.be/Bne7I910g2E", teluguPdfUrl: `${BASE}/2026/01/Dasakam74_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam74_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam74_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 75 – Kamsa Vadhā", videoUrl: "https://youtu.be/lM4r-gGpLPc", teluguPdfUrl: `${BASE}/2025/12/Dasakam75_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam75_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam75_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 76 – Udhāvaḍhotyam", videoUrl: "https://youtu.be/LNMvf2AZ5HA", teluguPdfUrl: `${BASE}/2025/12/Dasakam76_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam76_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam76_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 77 – Jarāsaṃdhādibhī yudhām", videoUrl: "https://youtu.be/xdHz84oGRAc", teluguPdfUrl: `${BASE}/2025/12/Dasakam77_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam77_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam77_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 78 – Rukminīsandesam", videoUrl: "https://youtu.be/BV08nM1y7Y0", teluguPdfUrl: `${BASE}/2025/12/Dasakam78_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam78_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam78_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 79 – Rukminīsvayamvaram", videoUrl: "https://youtu.be/pB4NL2NcPwo", teluguPdfUrl: `${BASE}/2025/12/Dasakam79_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam79_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam79_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 80 – Syamnatkopākhyānam", videoUrl: "https://youtu.be/I_PgoFNsZSU", teluguPdfUrl: `${BASE}/2025/12/Dasakam80_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam80_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam80_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 81 – Narākāsuravadhā", videoUrl: "https://youtu.be/mCsSmtI0aRM", teluguPdfUrl: `${BASE}/2025/12/Dasakam81_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam81_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam81_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 82 – Bānāsurayudham", videoUrl: "https://youtu.be/nthP9LUJTz0", teluguPdfUrl: `${BASE}/2025/12/Dasakam82_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam82_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam82_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 83 – Pauṇḍrakavadhā", videoUrl: "https://youtu.be/hzI0ReRaOPI", teluguPdfUrl: `${BASE}/2025/12/Dasakam83_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam83_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam83_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 84 – Samantakapancakayāṭrā", videoUrl: "https://youtu.be/8R6_OkAJxdU", teluguPdfUrl: `${BASE}/2025/12/Dasakam84_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam84_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam84_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 85 – Sisupālavadha", videoUrl: "https://youtu.be/LxpxNUfr0EQ", teluguPdfUrl: `${BASE}/2025/12/Dasakam85_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam85_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam85_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 86 – Mahābhāratayudhām", videoUrl: "https://youtu.be/shATDlyepZ4", teluguPdfUrl: `${BASE}/2026/01/Dasakam86_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam86_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam86_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 87 – Kucelopākhyānam", videoUrl: "https://youtu.be/nRzEa7py4iI", teluguPdfUrl: `${BASE}/2025/12/Dasakam87_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam87_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam87_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 88 – Arjunagarvabhangam", videoUrl: "https://youtu.be/hDfyTt7Jr4I", teluguPdfUrl: `${BASE}/2025/12/Dasakam88_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam88_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam88_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 89 – Vṛkāsuravadhām – Bruguparikṣanam", videoUrl: "https://youtu.be/KAnZ90MfaXo", teluguPdfUrl: `${BASE}/2025/12/Dasakam89_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam89_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam89_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 90 – Viṣanūmahatvam", videoUrl: "https://youtu.be/cFtCKUcoMG4", teluguPdfUrl: `${BASE}/2025/12/Dasakam90_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam90_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam90_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 91 – Bhakti svarūpavarṇanamu", videoUrl: "https://youtu.be/fMr0Vj3B1h8", teluguPdfUrl: `${BASE}/2026/01/Dasakam91_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam91_Telugu.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam91_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 92 – Karmamiśra bhakti svarūpamu", videoUrl: "https://youtu.be/7dvikF8-hpg", teluguPdfUrl: `${BASE}/2025/12/Dasakam92_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam92_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam92_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 93 – 24 Guru – Iruvadinālugumondi guruvulu", videoUrl: "https://youtu.be/_0qoeQETx6s", teluguPdfUrl: `${BASE}/2025/12/Dasakam93_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam93_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam93_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 94 – Tatvajñānōtapatti", videoUrl: "https://youtu.be/bgrYGVwBjV4", teluguPdfUrl: `${BASE}/2025/12/Dasakam94_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam94_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam94_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 95 – Dhyānayōgamu", videoUrl: "https://youtu.be/xpSmXabfHb8", teluguPdfUrl: `${BASE}/2026/01/Dasakam95_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam95_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam95_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 96 – Bhagavadiibhūti – bhaktiyōgamu", videoUrl: "https://youtu.be/BR1Qo837sdM", teluguPdfUrl: `${BASE}/2025/12/Dasakam96_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam96_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam96_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 97 – Uttamabhaktataprārthana, mārkaṇḍēyōpākhyānamu", videoUrl: "https://youtu.be/x3n9orOAIzY", teluguPdfUrl: `${BASE}/2026/01/Dasakam97_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam97_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam97_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 98 – kesadipadanta rupavarnanam", videoUrl: "https://youtu.be/a4nTS6dozns", teluguPdfUrl: `${BASE}/2026/01/Dasakam98_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam98_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam98_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 99 – Bhagavanihima", videoUrl: "https://youtu.be/k_1-zXWdA_g", teluguPdfUrl: `${BASE}/2025/12/Dasakam99_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam99_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam99_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
    { name: "Dasakam 100 – Kēśādipādāntarūpavarṇanamu", videoUrl: "https://youtu.be/E2_u5WQDA0E", teluguPdfUrl: `${BASE}/2025/12/Dasakam100_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2026/01/Dasakam100_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2026/01/Dasakam100_Sanskrit.pdf`, subcategory: "Narayaneeyam" },
  ],
  surya: [
    { name: "Aditya Hrudayam", videoUrl: "https://youtu.be/TcWmQ2BPmbE", teluguPdfUrl: `${BASE}/2024/09/Aditya_Hrydayam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Aditya_Hrydayam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/09/Aditya_Hrydayam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/09/Aditya_Hrydayam_Sanskrit.pdf` },
  ],
  guru: [
    { name: "Guru Ashtakam", teluguPdfUrl: `${BASE}/2024/08/Guru_Ashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Guru_Ashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Guru_Ashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Guru_Ashtakam_Sanskrit.pdf` },
    { name: "Guruparampara", teluguPdfUrl: `${BASE}/2024/08/Guruparampara_Stotram_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Guruparampara_Stotram_Englsih.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Guruparampara_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Guruparampara_Stotram_Sanskrit.pdf` },
    { name: "Hara Haa Sankara! Jaya Jaya Sankara!", teluguPdfUrl: `${BASE}/2024/08/HaraHara_Sankara_Jayajaya_Sankara_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/HaraHara_Sankara_Jayajaya_Sankara_English.pdf`, kannadaPdfUrl: `${BASE}/2024/08/HaraHara_Sankara_Jayajaya_Sankara_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/HaraHara_Sankara_Jayajaya_Sankara_Sanskrit.pdf` },
    { name: "Maatru Panchakam", videoUrl: "https://youtu.be/hjYaEB2APIM", teluguPdfUrl: `${BASE}/2024/08/MatruPanchakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Matru-Panchakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Matru-Panchakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Matru-Panchakam_Sanskrit.pdf` },
    { name: "Sadguru Dasakam", videoUrl: "https://youtu.be/XEjqfrMw5nM", teluguPdfUrl: `${BASE}/2024/08/Sadguru_Dasakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/SadguruDasakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/08/SadguruDasakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/SadguruDasakam_Sanskrit.pdf` },
    { name: "Sri Chandrasekara Gurushthuti Panchakam", teluguPdfUrl: `${BASE}/2024/12/SriChandraseka_Gurusthuti_Punchakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/12/SriChandraseka_Gurusthuti_Punchakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/12/SriChandraseka_Gurusthuti_Punchakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/12/SriChandraseka_Gurusthuti_Punchakam_Sanskrit.pdf` },
    { name: "Totakashtakam", teluguPdfUrl: `${BASE}/2024/08/Totakashtakam_Telugu.pdf`, englishPdfUrl: `${BASE}/2024/08/Totakashtakam_English.pdf`, kannadaPdfUrl: `${BASE}/2024/08/Totakashtakam_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2024/08/Totakashtakam_Sanskrit.pdf` },
  ],
  hanuman: [
    { name: "Panchamukha Hanuman Stotram", videoUrl: "https://youtu.be/HBtsoLlIYrM", teluguPdfUrl: `${BASE}/2025/11/Panchamukha_Hanuman_Stotram.pdf`, englishPdfUrl: `${BASE}/2025/11/Panchamukha_Hanuman_Stotram_English.pdf`, kannadaPdfUrl: `${BASE}/2025/11/Panchamukha_Hanuman_Stotram_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/11/Panchamukha_Hanuman_Stotram_Sanskrit.pdf` },
    { name: "Hanuman Stotram Veebhishanakrutha", videoUrl: "https://youtu.be/lCwJCbjK-Dc", teluguPdfUrl: `${BASE}/2025/04/Hanuman_Stotram_Veebhishanakrutha_Telugu.pdf`, kannadaPdfUrl: `${BASE}/2025/04/Hanuman_Stotram_Veebhishanakrutha_Kannada.pdf`, sanskritPdfUrl: `${BASE}/2025/04/Hanuman_Stotram_Veebhishanakrutha_Sanskrit.pdf` },
  ],
};

export async function seedDatabase() {
  try {
    if (!process.env.DATABASE_URL) {
      log("Using file-based storage, no seeding needed", "seed");
      return;
    }

    const count = await storage.getCategoryCount();
    if (count > 0) {
      for (const catData of categoriesData) {
        await storage.updateCategorySortOrder(catData.slug, catData.sortOrder);
      }

      let added = 0;
      for (const [slug, stots] of Object.entries(stotramsByCategory)) {
        const cat = await storage.getCategoryBySlug(slug);
        if (!cat) continue;
        const existing = await storage.getStotramsByCategory(cat.id);
        const existingNames = new Set(existing.map((s: any) => s.name));
        for (let i = 0; i < stots.length; i++) {
          const s = stots[i];
          if (!existingNames.has(s.name)) {
            await storage.insertStotram({
              categoryId: cat.id,
              name: s.name,
              subcategory: s.subcategory || null,
              videoUrl: s.videoUrl || null,
              teluguPdfUrl: s.teluguPdfUrl || null,
              englishPdfUrl: s.englishPdfUrl || null,
              kannadaPdfUrl: s.kannadaPdfUrl || null,
              sanskritPdfUrl: s.sanskritPdfUrl || null,
              sortOrder: i + 1,
            });
            added++;
          }
        }
      }

      log(`Database synced: sort orders updated, ${added} missing stotrams added`, "seed");
      return;
    }

    log("Seeding database...", "seed");

    const categoryMap = new Map<string, number>();

    for (const catData of categoriesData) {
      const cat = await storage.insertCategory(catData);
      categoryMap.set(catData.slug, cat.id);
    }

    for (const [slug, stots] of Object.entries(stotramsByCategory)) {
      const categoryId = categoryMap.get(slug);
      if (!categoryId) continue;

      for (let i = 0; i < stots.length; i++) {
        const s = stots[i];
        await storage.insertStotram({
          categoryId,
          name: s.name,
          subcategory: s.subcategory || null,
          videoUrl: s.videoUrl || null,
          teluguPdfUrl: s.teluguPdfUrl || null,
          englishPdfUrl: s.englishPdfUrl || null,
          kannadaPdfUrl: s.kannadaPdfUrl || null,
          sanskritPdfUrl: s.sanskritPdfUrl || null,
          sortOrder: i + 1,
        });
      }
    }

    log("Database seeded successfully!", "seed");
  } catch (err) {
    console.error("Seed error:", err);
  }
}
